# build_readme.ps1
# Gera o README.md a partir do characters-api.json (gere a API antes!).
# Ler os dados do JSON garante que README e API estejam sempre em sincronia.
# O README gerado serve de onboarding completo: qualquer pessoa (ou assistente IA)
# que o ler entende o projeto inteiro e é direcionada ao Memoria.md.

$ErrorActionPreference = 'Stop'
# Raiz do projeto = pasta PAI do script (o script vive em scripts/).
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')).TrimEnd('\')

$apiPath = Join-Path $root 'characters-api.json'
if (-not (Test-Path -LiteralPath $apiPath)) {
  throw "characters-api.json nao encontrado. Execute build_api_json.ps1 primeiro."
}
$api = [System.IO.File]::ReadAllText($apiPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$firstGroupFolder = if ($api.groups.Count -gt 0) { $api.groups[0].folder } else { '00_Indefinido' }
$lastGroupFolder = if ($api.groups.Count -gt 0) { $api.groups[-1].folder } else { '00_Indefinido' }

$L = New-Object System.Collections.Generic.List[string]
$L.Add('# README - Aetheria Codex')
$L.Add('')
$L.Add('> 🤖 **Para assistentes de IA (Claude e similares):** ao iniciar uma conversa sobre este projeto, leia este README por inteiro para entender a estrutura, E DEPOIS LEIA [`Memoria.md`](Memoria.md) — é a linha do tempo oficial com todas as alterações, erros já resolvidos, lições técnicas (armadilhas de PowerShell 5.1) e pendências. Ao terminar qualquer manutenção, adicione uma entrada lá com data/hora e commit.')
$L.Add('')
$L.Add('> 💡 **Prompt sugerido para iniciar uma nova conversa:** *"Leia o README.md e o Memoria.md deste projeto para absorver todo o contexto antes de qualquer tarefa."*')
$L.Add('')
$L.Add('---')
$L.Add('')
$L.Add('## O que é este projeto')

$L.Add('')
$L.Add('**Aetheria Codex** é um códice de personagens de fantasia autoral: **' + $api.totalCharacters + ' personagens** distribuídos em **' + $api.totalGroups + ' categorias/raças**, cada um com ficha em Markdown (história + descrição visual detalhada) e arte `.png`. Sobre esse acervo roda um site galeria estático — sem backend, sem dependências, só HTML/CSS/JS puro.')
$L.Add('')
$L.Add('O fluxo é: **fichas `.md` nas pastas → scripts PowerShell geram `characters-api.json` e `README.md` → `index.html` consome a API JSON**.')
$L.Add('')
$L.Add('## 📸 Galeria do Site')
$L.Add('')
$L.Add('**Home — hero com stats e destaque do dia** (tema claro): contadores animados (' + $api.totalCharacters + ' personagens · ' + $api.totalGroups + ' raças), destaque determinístico pelo dia do ano (com reroll 🎲) e CTAs para o mapa e "Surpreenda-me".')
$L.Add('')
$L.Add('![Home — hero com destaque do dia](docs/screenshots/index-hero.jpg)')
$L.Add('')
$L.Add('**Cards "Carta do Códice"** (tema escuro): moldura de manuscrito com cantos que crescem no hover, tilt 3D, foil holográfico que segue o ponteiro, filete e badge na cor da raça, blur-up das artes.')
$L.Add('')
$L.Add('![Cards-carta com foil holo](docs/screenshots/index-cards.jpg)')
$L.Add('')
$L.Add('**Filtro por raça:** chips compactos em linha rolável; o ativo é preenchido com a cor da categoria (aqui Onis) e a seleção fica na URL (`#g=04_Onis`) — deep-link compartilhável.')
$L.Add('')
$L.Add('![Filtro por raça ativo](docs/screenshots/index-filtros.jpg)')
$L.Add('')
$L.Add('**Modal folheável:** morf card→modal (View Transitions), abas 📜 História (com lore da raça) e 🧬 Ficha técnica, navegação ‹ › + teclas ←→ com contador "N / M", copiar link e focus trap.')
$L.Add('')
$L.Add('![Modal folheável do personagem](docs/screenshots/index-modal.jpg)')
$L.Add('')
$L.Add('**Paleta de comandos (Ctrl+K ou /):** busca fuzzy insensível a acentos com ranking global — personagens, raças e ações no mesmo resultado (digitar "aat" já traz o Aatrox).')
$L.Add('')
$L.Add('![Paleta de comandos Ctrl+K](docs/screenshots/index-palette.jpg)')
$L.Add('')
$L.Add('**Mapa "Mesa de Guerra Arcana":** mundo 3D em Canvas 2D puro (sem bibliotecas), câmera orbital (arrasto/roda/pinça) e 26 pins — 16 regiões, 5 batalhas e 5 céus — alimentados pelo `historia-api.json`.')
$L.Add('')
$L.Add('![Mapa do mundo em 3D](docs/screenshots/mapa.jpg)')
$L.Add('')
$L.Add('**Outros ângulos da câmera orbital** — arrastar gira e inclina o mundo; aqui em vista girada, com os penhascos do relevo em primeiro plano e a geleira à direita:')
$L.Add('')
$L.Add('![Mapa em ângulo girado](docs/screenshots/mapa-girado.jpg)')
$L.Add('')
$L.Add('**Pin selecionado:** o painel lateral traz a lore do local (aqui as Cavernas de Obsidiana, casa dos Onis) e o chip HABITANTES com a contagem de personagens — clicável, leva à galeria já filtrada.')
$L.Add('')
$L.Add('![Painel de lore do pin aberto](docs/screenshots/mapa-pin.jpg)')
$L.Add('')
$L.Add('**Vista rasante:** com a câmera quase na horizontal o relevo aparece de perfil — penhascos em silhueta, vulcão com lava emissiva e os pins dos céus flutuando sobre o mundo.')
$L.Add('')
$L.Add('![Mapa em vista rasante](docs/screenshots/mapa-rasante.jpg)')
$L.Add('')
$L.Add('**Página de raça** (1 das ' + $api.totalGroups + ', todas geradas por `scripts\\build_racas.ps1`): herói rotativo com autoplay, reveal por caractere, tilt/glare na arte, chips de atributos e deep-link por personagem.')
$L.Add('')
$L.Add('![Página de raça — herói rotativo](docs/screenshots/raca-hero.jpg)')
$L.Add('')
$L.Add('**Acervo da raça:** todos os membros clicáveis (abrem o herói), navegação entre as ' + $api.totalGroups + ' raças e dados embutidos na própria página — funciona até abrindo o arquivo direto (`file://`).')
$L.Add('')
$L.Add('![Acervo completo da raça](docs/screenshots/raca-acervo.jpg)')
$L.Add('')
$L.Add('## ✨ Features Q4/2026 — Galeria Visual')
$L.Add('')
$L.Add('Capturas dedicadas das **17 funcionalidades entregues no ciclo Q4/2026** — cada bloco descreve **o que o usuário vê** + **como a captura foi produzida**. Para os detalhes internos de cada feature, ver "🖥️ Como as Telas Funcionam" abaixo (mesmo marcador §X.X).')
$L.Add('')
$L.Add('### A. Onboarding & Descoberta (desktop)')
$L.Add('')
$L.Add('**Toast instrutivo do botão "📲 Instalar"** — detecção adaptativa por UA, com 3 variantes (Chromium, iOS Safari, fallback) e micro-copy distinta por engine.')
$L.Add('![Toast instrutivo do botao PWA](docs/screenshots/feat-pwa-install-toast.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o IIFE `installPwa()` (`index.html` ~linha 3303) testa `beforeinstallprompt` (Chromium), `navigator.standalone` (iOS) e cai num toast genérico nos demais; aparece em 7s e some sozinho, só na 1ª visita.')
$L.Add('*Implementação:* capturado com `page.evaluate(() => localStorage.clear())` + reload, viewport 1600x1000, servidor :8080; o Chromium dispara `beforeinstallprompt` mesmo sem o usuário instalar.')
$L.Add('*Tecnologias:* `beforeinstallprompt` event, `e.preventDefault()` (sem isso o Chrome mata o gatilho nativo), `navigator.standalone`, `setTimeout(..., 7000)`, classes `.toast`/`.toast--ios`/`.toast--fallback`.')
$L.Add('*Decisão:* iOS não dispara `beforeinstallprompt` — sem o toast instrutivo, o usuário iOS nunca descobriria "Compartilhar → Adicionar à Tela de Início" (§3.3 Q4).')
$L.Add('')
$L.Add('**Onboarding 4 passos — tela 1 (Bem-vindo)** — overlay central com 4 dots, botões prev/next/skip, micro-copy de boas-vindas.')
$L.Add('![Onboarding 4 passos - tela 1](docs/screenshots/feat-onboarding-passo1.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* `<div id="onboardOverlay">` em `position:fixed` com backdrop `rgba(0,0,0,.65)`; o passo atual (1/4) é destacado e o progresso fica visível nos 4 dots animados.')
$L.Add('*Implementação:* capturado com `localStorage.removeItem("aetheria.onboarded")` + reload (Playwright), viewport 1600x1000, sem flag de pupulação — é a 1ª visita real.')
$L.Add('*Tecnologias:* `localStorage["aetheria.onboarded"]` com `version:"1"` (só mostra de novo se `version !== "1"`), `.is-active` na `.onboard-step[n]`, `@keyframes onboardFadeIn`.')
$L.Add('*Decisão:* 4 passos com 4 saídas (Pular / Esc / backdrop / último Next = "Começar a explorar") para respeitar tanto apressados quanto curiosos — todos persistem em `localStorage` (§4.3 Q4).')
$L.Add('')
$L.Add('**Onboarding 4 passos — tela 2 após click em Next** — mesma estrutura, micro-copy de "Explore o códice", dot 2/4 ativo.')
$L.Add('![Onboarding 4 passos - tela 2 apos Next](docs/screenshots/feat-onboarding-passo2.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o click em Next incrementa o índice, troca o conteúdo do overlay e move o dot ativo com transição CSS de `transform: translateX`; o estado do passo é local (não persiste até o último Next).')
$L.Add('*Implementação:* capturado com `page.click("#onboardNext")` + `waitForTimeout(300)` (Playwright) para garantir a transição antes do screenshot.')
$L.Add('*Tecnologias:* mesmo overlay do passo 1, `aria-live="polite"` no conteúdo, foco automático no botão Next para navegação por teclado.')
$L.Add('*Decisão:* a animação do dot é a única pista visual de progresso — sem ela, o usuário não saberia que ainda há 2 passos (§4.3 Q4).')
$L.Add('')
$L.Add('**Skip-link a11y (Tab pressionado na home)** — o link "Pular para conteúdo principal" aparece no canto superior esquerdo, com outline visível.')
$L.Add('![Skip-link a11y com Tab pressionado](docs/screenshots/feat-skiplink.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o `<a href="#mainContent" class="skipLink">` é o primeiro elemento focável do `<body>`; ao receber foco ele ganha `transform: translate(0,0)` e outline `:focus-visible`.')
$L.Add('*Implementação:* capturado com `page.keyboard.press("Tab")` logo após o `goto`, em viewport 1600x1000, sem mouse — só o foco de teclado ativa o link.')
$L.Add('*Tecnologias:* `:focus-visible`, `transform: translateY(-100%)` → `translateY(0)`, atributo `id="mainContent"` no `<main>`, ARIA `aria-label="Pular para conteúdo principal"`.')
$L.Add('*Decisão:* WCAG 2.4.1 (Bypass Blocks) — o usuário de teclado/tecnologia assistiva pula a navegação sem tabular por 30+ chips antes do conteúdo (§4.1 Q4).')
$L.Add('')
$L.Add('### B. Galeria Aprimorada (desktop)')
$L.Add('')
$L.Add('**Diário de Páginas expandido: 3 mini-cards por período** — Manhã/Tarde/Noite abaixo do destaque principal; o card do período atual tem borda tingida na cor da raça.')
$L.Add('![Diario de Paginas expandido 3 mini-cards](docs/screenshots/feat-daily-featured-3p.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o seed do dia (YYYY-MM-DD) gera 3 personagens determinísticos (1 por período: ☀️ Manhã 5-12h / 🌤️ Tarde 12-18h / 🌙 Noite 18-5h); o card do período corrente (baseado no horário local) recebe classe `.is-now` com borda + fundo na cor da raça dele.')
$L.Add('*Implementação:* capturado com `page.addInitScript(() => { Date.now = () => 1700000000000 })` no Playwright para forçar 14h, mostrando a Tarde ativa; screenshot full-viewport 1600x1000.')
$L.Add('*Tecnologias:* `Intl.DateTimeFormat().hour`, hash determinístico sobre `seed + periodIndex`, CSS `border: 2px solid var(--race-color)` via `themes.json`.')
$L.Add('*Decisão:* 1 destaque → 3 opções reduz a fricção de reroll manual; o usuário sempre vê um personagem "do seu turno" sem precisar clicar 🎲 (§4.5 Q4).')
$L.Add('')
$L.Add('**Modal scrollado mostrando os 3 botões Share / Copiar link / Embed** — ações de compartilhamento do personagem, cada uma com ícone e micro-copy próprios.')
$L.Add('![Modal com 3 botoes de share](docs/screenshots/feat-modal-share-3botoes.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* os 3 botões ficam no rodapé da ficha técnica do modal: `#modalShare` usa Web Share API, `#modalShareBtn` usa Clipboard API, `#embedBtn` gera `<iframe>` 400×500 com `loading="lazy"`. Toast de confirmação em todos.')
$L.Add('*Implementação:* capturado com `page.click(".character-card")` para abrir o modal, depois `page.evaluate(() => { const m = document.querySelector("#modal"); m.scrollTop = m.scrollHeight; })` para revelar os 3 botões.')
$L.Add('*Tecnologias:* `navigator.share({title, text, url})`, `navigator.clipboard.writeText(url)`, `URL.createObjectURL` para o `<iframe>` blob, toast genérico `.toast--success`.')
$L.Add('*Decisão:* 3 caminhos cobrem 3 públicos (mobile share, link copy para chat, embed para blog/wiki) — Web Share sozinho exclui desktop e quem quer embedar (§4.4 Q4).')
$L.Add('')
$L.Add('**Dialog "Sobre" do footer** — `<dialog>` nativo com 4 seções (contagens vivas, lista de features, atalhos de teclado, "como tudo é construído").')
$L.Add('![Dialog Sobre do footer](docs/screenshots/feat-about-dialog.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* `<dialog id="aboutDialog">` aberto por `showModal()` via click no `#aboutLink`; Esc / click-fora / × fecham; scroll travado no `<body>` enquanto aberto.')
$L.Add('*Implementação:* capturado com `page.click("#aboutLink")` + `waitForSelector("#aboutDialog[open]")` em viewport 1600x1000.')
$L.Add('*Tecnologias:* HTML `<dialog>` (não `<div role=dialog>`), `dialog::backdrop`, contador animado `requestAnimationFrame`, atalhos listados com `<kbd>`.')
$L.Add('*Decisão:* `<dialog>` nativo dá focus trap + Esc de graça; reimplementar com JS puro seria esquecer a borda semântica e provavelmente o backdrop (§5.5 Q4).')
$L.Add('')
$L.Add('**Paleta de comandos aberta (Ctrl+K)** — busca fuzzy com ranking global, 3 tipos no mesmo resultado (personagens, raças, ações).')
$L.Add('![Paleta Ctrl+K aberta](docs/screenshots/feat-palette.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* modal central com `<input>` focado automaticamente; cada keystroke recalcula o ranking fuzzy insensível a acentos e rerenderiza a lista agrupada por tipo (desempate: personagem > raça > ação).')
$L.Add('*Implementação:* capturado com `page.keyboard.press("Control+k")` (ou `Meta+k` no macOS); o input "aat" foi digitado para mostrar o Aatrox no topo do ranking.')
$L.Add('*Tecnologias:* ARIA `role="combobox"`, matching fuzzy com normalização NFD + remoção de diacríticos, `aria-activedescendant` + live region.')
$L.Add('*Decisão:* "aat" traz o Aatrox entre Demônios — provar que a busca é global, não escopada por filtro ativo, é o que diferencia a paleta de um `<select>` comum.')
$L.Add('')
$L.Add('### C. Mapa & Linha do Tempo (desktop)')
$L.Add('')
$L.Add('**Mapa com filtro de raça (Onis) ativo** — pins das outras raças esmaecidos, chip "Onis" destacado com a cor canônica.')
$L.Add('![Mapa com filtro de raca Onis](docs/screenshots/feat-mapa-filtro-raca.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o chip de filtro aplica `opacity:0.25` aos pins cujo `data-race` não bate com a raça selecionada, com transição CSS de 200ms; o chip ativo é preenchido com a cor de `themes.json`.')
$L.Add('*Implementação:* capturado via `page.evaluate(() => location.hash = "#04_Onis")` (deep-link) + reload, depois `window.__MAPA__.abrir("Cavernas_de_Obsidiana")` no console para pré-abrir o painel da região dos Onis.')
$L.Add('*Tecnologias:* querySelector sobre `g[data-race]`, custom property `--race-onis`, hashchange listener, API de diagnóstico `window.__MAPA__` (`abrir`, `camera`, `estado`, `ids`, `exportarVista`).')
$L.Add('*Decisão:* o filtro via hash fecha o circuito mapa ↔ galeria ↔ APIs — o mesmo `#<folder>` funciona nos dois lados (§6.3 Q4).')
$L.Add('')
$L.Add('**Linha do Tempo narrativa do mundo** — 4 atos cinematográficos com Ken Burns nos quadros de batalha, do ano 0 ao ano 12.')
$L.Add('![Linha do tempo narrativa](docs/screenshots/feat-linha-do-tempo.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* página dedicada com timeline horizontal scrollável; cada ato é uma seção fullscreen com parallax sutil e revel por caractere nos títulos.')
$L.Add('*Implementação:* capturado em `Linha_do_Tempo.html` servido por `python -m http.server 8080`, viewport 1600x1000, com scroll para o início do Ato 2 (Guerra da Fenda) para mostrar um quadro de batalha.')
$L.Add('*Tecnologias:* `historia-api.json` (mesma fonte do mapa), `assets/timeline.css` + `assets/timeline-data.js`, `requestAnimationFrame` para o Ken Burns, `IntersectionObserver` para o reveal.')
$L.Add('*Decisão:* consome a mesma `historia-api.json` do mapa — mudar a lore em `Aetheria_Dados_do_Mundo.md` reflete nos dois sem retrabalho (§9.1 Q4).')
$L.Add('')
$L.Add('### D. Mobile (390×844) — paridade das features')
$L.Add('')
$L.Add('Todas as 7 capturas abaixo comprovam que **nada do Q4/2026 é só desktop** — onboarding, filtros, modal, paleta, mapa, timeline e about dialog têm paridade responsiva.')
$L.Add('')
$L.Add('**Onboarding mobile (390×844)** — mesmo overlay de 4 passos, mas o conteúdo ocupa quase toda a viewport; botão Next com target ≥44px.')
$L.Add('![Onboarding mobile](docs/screenshots/feat-mob-onboarding.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o overlay usa `width: min(92vw, 480px)` e padding maior; os botões ficam empilhados verticalmente para acomodar o polegar.')
$L.Add('*Implementação:* capturado em viewport 390×844 (iPhone 14), `localStorage.removeItem("aetheria.onboarded")` + reload, `isMobile: true` + `hasTouch: true` no contexto Playwright.')
$L.Add('*Tecnologias:* `min(92vw, 480px)`, `@media (max-width: 720px)`, `touch-action: manipulation`, target `min-height: 44px`.')
$L.Add('*Decisão:* alvo ≥44px (WCAG 2.5.5) e empilhamento evitam o "erro do polegar" em 1ª visita no celular.')
$L.Add('')
$L.Add('**Cards mobile filtrados por Demônios (05)** — grade 1-coluna com chips de raça condensados no topo rolável.')
$L.Add('![Cards mobile filtrados por Demonios](docs/screenshots/feat-mob-cards-demonios.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* a grade vira `grid-template-columns: 1fr` abaixo de 720px; os chips de filtro viram uma faixa horizontal com `scroll-snap-type: x mandatory`.')
$L.Add('*Implementação:* capturado após `page.goto("index.html#g=05_Demonios")` em viewport 390×844, scroll para a região da grade.')
$L.Add('*Tecnologias:* CSS Grid `grid-template-columns: 1fr`, `scroll-snap-type: x mandatory` no carrossel de chips, blur-up mantido.')
$L.Add('*Decisão:* 1 coluna no mobile preserva o tilt 3D do card sem cortar a moldura de manuscrito nos 390px de largura.')
$L.Add('')
$L.Add('**Modal mobile** — ocupa 100% da viewport, swipe touch para próximo/anterior personagem.')
$L.Add('![Modal mobile](docs/screenshots/feat-mob-modal.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o modal ganha `width: 100vw; height: 100dvh; border-radius: 0` abaixo de 720px; swipe horizontal dispara `stepModal(±1)` com threshold de 50px.')
$L.Add('*Implementação:* capturado com `page.click(".character-card")` em viewport 390×844, após `window.scrollTo(0, 800)` para garantir card visível.')
$L.Add('*Tecnologias:* `touchstart`/`touchend` em `#modalMedia` com `Math.abs(deltaX) > 50`, `100dvh` (dynamic viewport height), `stepModal()` reusado das setas.')
$L.Add('*Decisão:* no mobile, as setas ‹ › somem e o swipe vira o gesto natural — o handler reusa a mesma função das setas para evitar drift de lógica.')
$L.Add('')
$L.Add('**Paleta mobile (ativada com "/")** — vira folha inferior (bottom sheet) com 92vw de largura, input com `inputmode="search"`.')
$L.Add('![Paleta mobile](docs/screenshots/feat-mob-palette.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* abaixo de 720px a paleta troca de modal central para bottom sheet ancorado no rodapé; o atalho "/" funciona mesmo com teclado virtual aberto.')
$L.Add('*Implementação:* capturado com `page.keyboard.press("/")` em viewport 390×844, após focar no body (não em um input) para evitar conflito com a barra do navegador.')
$L.Add('*Tecnologias:* `transform: translateY(100%) → 0`, `inputmode="search"`, `autocapitalize="off"`, `autocomplete="off"`, listener `keydown` no `document`.')
$L.Add('*Decisão:* Ctrl+K é awkward no celular (sem Ctrl físico); "/" é o atalho canônico do Spotlight/Gmail-mobile e já era parte do spec.')
$L.Add('')
$L.Add('**Mapa mobile (390×844)** — Canvas 2D com pinça (2 dedos) e toque longo para abrir painel, câmera com limites de pitch para não furar o relevo.')
$L.Add('![Mapa mobile](docs/screenshots/feat-mob-mapa.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* a câmera responde a `touchstart`/`touchmove`/`touchend` com 1 dedo = orbital, 2 dedos = pan + zoom; o painel de lore vira um sheet inferior.')
$L.Add('*Implementação:* capturado em `Mapa_Aetheria.html` viewport 390×844, com `window.__MAPA__.camera({yaw: 0.3, pitch: 0.8, dist: 1.4})` para uma vista 3/4 de boa legibilidade.')
$L.Add('*Tecnologias:* `TouchEvent.touches`, distância euclidiana entre 2 dedos para zoom, `pointer-events: none` no sheet inferior quando fechado, debounce de 16ms.')
$L.Add('*Decisão:* Canvas 2D puro escala sem custo (zero deps), e os 2 modos de toque não conflitam com o scroll da página (`touch-action: none` só no canvas).')
$L.Add('')
$L.Add('**Linha do Tempo mobile** — timeline vertical com cards empilhados, Ken Burns preservado nos quadros.')
$L.Add('![Linha do tempo mobile](docs/screenshots/feat-mob-linha-do-tempo.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* a timeline horizontal vira vertical (`flex-direction: column`) abaixo de 720px; os atos ocupam `min-height: 100dvh` cada para preservar o ritmo cinematográfico.')
$L.Add('*Implementação:* capturado em `Linha_do_Tempo.html` viewport 390×844, com scroll para o Ato 3 (Erupção do Abismo) onde o vulcão com lava emissiva é mais visível.')
$L.Add('*Tecnologias:* `@media (orientation: portrait)` + `flex-direction: column`, `scroll-snap-type: y mandatory` opcional, Ken Burns com `transform-origin: center`.')
$L.Add('*Decisão:* a inversão horizontal→vertical é mandatória no portrait — manter horizontal forçaria o usuário a girar o celular pra cada ato.')
$L.Add('')
$L.Add('**About dialog mobile** — `<dialog>` ocupando 100dvh, scroll interno no conteúdo (não no body).')
$L.Add('![About mobile](docs/screenshots/feat-mob-about.jpg)')
$L.Add('')
$L.Add('*Mecanismo:* o `<dialog>` ganha `width: 100vw; height: 100dvh; border-radius: 0` e o conteúdo interno rola com `overflow-y: auto` no próprio dialog (não no body).')
$L.Add('*Implementação:* capturado com `page.click("#aboutLink")` em viewport 390×844, scroll para a seção "Atalhos de teclado" para mostrar a lista de `<kbd>`.')
$L.Add('*Tecnologias:* `<dialog>` nativo + `100dvh`, `overscroll-behavior: contain` no conteúdo, `<kbd>` estilizado com borda inferior 2px.')
$L.Add('*Decisão:* scroll interno evita o "rubber-band" duplo (body + dialog) que dá em alguns Androids quando ambos rolam.')
$L.Add('')
$L.Add('## Estrutura do Projeto')
$L.Add('')
$L.Add('| Caminho | Função |')
$L.Add('|---|---|')
$L.Add('| `codex/` | As ' + $api.totalGroups + ' pastas numeradas (`codex\\' + $firstGroupFolder + '` a `codex\\' + $lastGroupFolder + '`) — uma categoria/raça por pasta; dentro, o arquivo `Aetheria_Codex_de_*.md` com as fichas + os PNGs/WebPs dos personagens |')
$L.Add('| `index.html` | Site galeria (tema claro/escuro, busca, filtros por categoria, modal folheável, PWA, onboarding, share/embed) — consome `characters-api.json` |')
$L.Add('| `Mapa_Aetheria.html` | Mapa 3D do mundo "Mesa de Guerra Arcana" (Canvas 2D puro, 26 pins, câmera orbital, filtro raça/era, export PNG) — consome `historia-api.json` |')
$L.Add('| `Linha_do_Tempo.html` | Linha do tempo narrativa do mundo (4 atos cinematográficos + 5 batalhas épicas) — gerada de `historia-api.json` |')
$L.Add('| `offline.html` | Página de fallback do Service Worker (offline-first) |')
$L.Add('| `racas/` | ' + $api.totalGroups + ' páginas de raça geradas pelo `scripts\\build_racas.ps1` — showcase rotativo dos membros, lore, acervo, rituais e navegação entre raças (dados embutidos, funciona em file://) |')
$L.Add('| `assets/` | Recursos estáticos compartilhados: `codex.css` (105 KB, 22 raças), `rituals.js` (10 rituais do modal), `transitions.js` (transições de página), `timeline.css`+`timeline-data.js`, subpastas `brand/`, `ornaments/`, `textures/`, `ui/`, `videos/`, ícones (favicon, apple-touch, og-cover) |')
$L.Add('| `data/` | Configs estáticas: `themes.json` (cor/ícone das 22 raças — fonte canônica única) + `characters.schema.json` (schema JSON da API) |')
$L.Add('| `Historia/` | Lore autoral do mundo (narrativa livre) + `Aetheria_Dados_do_Mundo.md`, a fonte estruturada da API da história (16 regiões, 5 batalhas, 5 celestes, 22 raças, 10 rituais) |')
$L.Add('| `characters-api.json` | API estática gerada — única fonte de dados do site (22 grupos, ' + $api.totalCharacters + ' personagens, sem array flat) |')
$L.Add('| `historia-api.json` | API estática da história (regiões, celestes, batalhas, raças e rituais) — consumida pelo mapa, racas e linha do tempo |')
$L.Add('| `manifest.webmanifest` | Manifesto PWA (3 ícones, 4 shortcuts, pt-BR) — gerado por `scripts\\build_manifest.ps1` |')
$L.Add('| `sw.js` | Service Worker (network-first p/ HTML, cache-first p/ assets, offline.html, `skipWaiting`+`clients.claim`) |')
$L.Add('| `Memoria.md` | 📌 Linha do tempo oficial do projeto: alterações, erros/correções, lições técnicas, pendências — LER PRIMEIRO em toda sessão |')
$L.Add('| `Temporario.md` | 📋 Backlog Q4/2026 consolidado (status dos 10 itens + 39 subitens do plano, próximas sugestões) |')
$L.Add('| `graphify-out/` | 🕸️ Grafo de conhecimento do projeto (skill `/graphify`) — ver seção própria abaixo |')
$L.Add('| `docs/` | `screenshots/` (28 capturas JPEG: 11 da galeria base + 17 da galeria Q4/2026) + `relatorio-arte.md` (gerado por `relatorio_arte.py`) |')
$L.Add('| `tests/` | 15 testes Node (Playwright) + 2 utilitários Python + 2 scripts Node utilitários — ver seção própria abaixo |')
$L.Add('| `scripts/` | 12 scripts PowerShell (build/mainutenção) + 3 utilitários Python (padronização/relatórios) — ver tabela dedicada abaixo |')
$L.Add('')
$L.Add('## 🖥️ Como as Telas Funcionam')
$L.Add('')
$L.Add('### `index.html` — galeria "Evolução Premium"')
$L.Add('')
$L.Add('- **Dados:** tudo vem do `characters-api.json` via `fetch()` (por isso precisa de servidor local — ver "Como Rodar o Site"). Sem backend, sem dependências.')
$L.Add('- **Hero:** contadores count-up em `requestAnimationFrame`, **destaque do dia determinístico** (dia-do-ano % total, reroll 🎲) e glow ambiente tingido pela cor da raça do destaque.')
$L.Add('- **Cards-carta:** tilt 3D com um único loop rAF para o card sob o cursor; foil holo `color-dodge` guiado pela posição do ponteiro (só em `hover: fine` e sem `prefers-reduced-motion`); blur-up das artes; primeira dobra com `fetchpriority=high`, resto lazy.')
$L.Add('- **Modal folheável:** morph card→modal via **View Transitions** (o `view-transition-name` é atribuído só durante a transição e limpo no fim — nome duplicado quebra o snapshot); abas História/Ficha; navegação por teclas ←→ sobre os resultados filtrados com deep-link `#<id>`; focus trap de verdade (Tab não escapa); lore da raça vem do `historia-api.json` (fetch tolerante a falha).')
$L.Add('- **Paleta Ctrl+K** (ou `/`): personagens + ' + $api.totalGroups + ' raças + ações num **mesmo ranking global** com desempate por tipo; matching fuzzy insensível a acentos; ARIA combobox completo; vira folha no mobile.')
$L.Add('- **URL state:** `#g=&q=&sort=&fav=` — compatível com deep-links antigos (`#<pasta>` do mapa e `#<personagem>`); filtros, busca e favoritos sobrevivem a reload e são compartilháveis.')
$L.Add('- **Auto-load:** sentinel com IntersectionObserver (rootMargin 900px) carrega mais cards ao rolar; o botão "Carregar mais" continua como fallback e é o caminho único com reduced-motion.')
$L.Add('- **Temas:** ' + $api.totalGroups + ' cores/ícones de raça aplicados a cards, modal, filtros e glow; claro/escuro (a 1ª visita respeita `prefers-color-scheme`); tema, favoritos e header fixado persistem em `localStorage`; personagem sem arte ganha placeholder local desenhado (monograma + hachura na cor da categoria).')
$L.Add('')
$L.Add('### `racas/*.html` — ' + $api.totalGroups + ' páginas de raça (geradas)')
$L.Add('')
$L.Add('- **Geradas por `scripts\\build_racas.ps1`** a partir da API — nunca edite os HTMLs à mão: mude o template do script e regenere. Guard interno confere a soma de membros contra o JSON.')
$L.Add('- **Dados embutidos** no payload `#race-data` dentro de cada página → funciona em `file://`, sem servidor e sem fetch.')
$L.Add('- **Herói rotativo:** autoplay de 7s com barra de progresso nos dots, trocas animadas por WAAPI, reveal do nome por caractere, tilt 3D + glare + Ken Burns na arte; a pausa por hover vale SÓ no palco (não na página inteira) e `focusin` pausa no herói todo (acessibilidade).')
$L.Add('- **Deep-link `#<id>`** abre direto no personagem (listener `hashchange` cobre navegação same-document); ficha lateral mostra os 6 atributos da ficha; acervo clicável; setas ‹ › e índice das ' + $api.totalGroups + ' raças; tema persistido em `localStorage.racasTheme`.')
$L.Add('- **Reveals à prova de falha:** o conteúdo nasce VISÍVEL no CSS; o estado oculto `.pre-reveal` só é aplicado via JS quando `IntersectionObserver` existe, com sweep de segurança de 900ms — sem JS ou com IO morto, nada fica invisível (lição do "bug dos reveals", ver `Memoria.md`).')
$L.Add('')
$L.Add('### `Mapa_Aetheria.html` — Mesa de Guerra Arcana')
$L.Add('')
$L.Add('- **Canvas 2D puro** (zero bibliotecas): heightmap procedural com biomas por região, câmera orbital (arrasto/roda/pinça/duplo-clique reset), painter algorithm com flat shading e névoa, lava conectada e veios emissivos.')
$L.Add('- **26 pins clicáveis** (16 regiões + 5 batalhas + 5 céus) consumindo `historia-api.json`, com fallback embutido completo para `file://` (o fetch é pulado sem ruído).')
$L.Add('- **Filtro por raça + era** (W5): chips de camada (Regiões / Batalhas / Céus) + filtro de raça (deep-link `#<folder>`) — fecha o circuito mapa↔galeria↔APIs.')
$L.Add('- **Rota narrativa entre pins** (§6.2 Q4): 5 batalhas encadeadas em 4 atos cinematográficos com transição visual; navegação pela timeline dentro do próprio mapa.')
$L.Add('- **Exportar vista como PNG** (§6.4 Q4): botão "📸 Salvar vista" gera `aetheria-mapa-<timestamp>.png` 1280×720 (esconde HUDs durante a captura e restaura no callback).')
$L.Add('- **Painel lateral** com a lore do local e chips HABITANTES/COMBATENTES que abrem a galeria filtrada (`index.html#<pasta>`).')
$L.Add('- **API de diagnóstico `window.__MAPA__`:** `estado()` (câmera, painel, camadas), `abrir(id)`, `camera({yaw,pitch,dist})`, `telaDePOI(id)`, `ids()` e `exportarVista()` — feita para testes automatizados; foi assim que as capturas de outros ângulos do README foram tiradas (o mapa é Canvas, pins não são elementos do DOM).')
$L.Add('')
$L.Add('### `Linha_do_Tempo.html` — narrativa do mundo')
$L.Add('')
$L.Add('- **4 atos cinematográficos + 5 batalhas** (Inverno Eterno → Guerra da Fenda → Erupção do Abismo → Verao do Vazio), do ano 0 ao ano 12.')
$L.Add('- Gerada a partir de `historia-api.json` (consome a mesma fonte do mapa) — funciona em `file://` via fallback.')
$L.Add('- Mesma estética dark-first das páginas de raça, com Ken Burns nos quadros de batalha e revel por caractere nos títulos.')
$L.Add('- `assets/timeline.css` + `assets/timeline-data.js` são os assets específicos desta página.')
$L.Add('')
$L.Add('### PWA & Service Worker')
$L.Add('')
$L.Add('- **Manifest** (`manifest.webmanifest`, gerado por `scripts\\build_manifest.ps1`): 3 ícones (192/32/180), 4 shortcuts (Mapa, Os Aspectos, Alvamortos, Demônios do Caos), `display: standalone`, `theme_color: #1a120e`, categorias `books/entertainment/lifestyle`, `lang: pt-BR`.')
$L.Add('- **Service Worker** (`sw.js`): network-first para HTML (versão nova sempre chega), cache-first para assets estáticos (`PRECACHE_URLS`), `MAX_RUNTIME=200` entradas, `skipWaiting` + `clients.claim` para atualização imediata, fallback `offline.html` quando o fetch falha.')
$L.Add('- **Botão "📲 Instalar" no header** (§3.3 Q4): detecta `beforeinstallprompt` (Chromium/Android/Desktop), iOS Safari via toast instrutivo de 7s ("Compartilhar → Adicionar à Tela de Início"), Firefox/outros via toast explicativo; some quando `display-mode: standalone` ou `navigator.standalone`.')
$L.Add('- **Fallback offline** (`offline.html`): página leve (1 KB de CSS próprio) servida pelo SW quando o fetch do HTML principal falha; mesmo tema dark-first do site.')
$L.Add('')
$L.Add('### Features de descoberta & UX')
$L.Add('')
$L.Add('- **Diário de Páginas diário expandido** (§4.5 Q4): 1 destaque → 3 mini-cards por período (☀️ Manhã 5-12h / 🌤️ Tarde 12-18h / 🌙 Noite 18-5h), determinístico por seed do dia; click no mini-card troca o destaque principal. O card do período atual fica com borda + fundo tingido na cor da raça.')
$L.Add('- **Cross-fade cinematográfico** (§4.6 Q4): troca de destaque usa 2 layers (`#current` / `#incoming`) com `featureArtOut` 700ms + `setTimeout` 730ms de cleanup (monotônico via token — cliques rápidos não corrompem estado). Sem WAAPI, só CSS keyframes + classes. Compatível com `prefers-reduced-motion`.')
$L.Add('- **Onboarding 4 passos** (§4.3 Q4): overlay com 4 passos (Bem-vindo / Explore o códice / Mapa & rituais / Buscar & favoritar), 4 dots, prev/next/skip, 4 caminhos de saída (Pular, Esc, backdrop, último Next); persistência em `localStorage["aetheria.onboarded"]` com `version:"1"`.')
$L.Add('- **Dialog "Sobre"** (§5.5 Q4): `<dialog id="aboutDialog">` com 4 seções (contagens vivas, lista de features, atalhos de teclado, "Como tudo é construído"); abre via `#aboutLink` no footer, fecha por Esc / click-fora / botão.')
$L.Add('- **Compartilhar (3 botões no modal)** (§4.4 Q4): `#modalShare` (SVG → Web Share API), `#modalShareBtn` (🔗 Copiar link, fallback clipboard), `#embedBtn` (📋 Embed, gera `<iframe>` 400×500 com `loading="lazy"`). Toast de confirmação em todos.')
$L.Add('- **A11y** (§4.1+§4.2 Q4): skip-link para `#mainContent`, MICRO_COPY personalizado para 22 raças, top-3 sugestões no empty-state dos filtros, contraste WCAG 4.5:1 em todas as 22 cores de tema (via `bestInk` com threshold `L > 0.18` calibrado), alvos ≥44px no touch, `prefers-reduced-motion` global zerando 6 media queries + guard JS, swipe touch no modal (handler `touchstart`/`touchend` em `#modalMedia` com threshold 50px reusando `stepModal`).')
$L.Add('- **Favoritos persistentes:** `localStorage.aetheriaFavs` (Set serializado como array), badge de coração tingido na cor da raça, atalho via paleta Ctrl+K (ação "Ver favoritos").')
$L.Add('')
$L.Add('## 📂 Scripts (`scripts/`)')
$L.Add('')
$L.Add('| Script | Função |')
$L.Add('|---|---|')
$L.Add('| `build_api_json.ps1` | 1. **OBRIGATÓRIO** — parseia `codex/*/Aetheria_Codex_de_*.md` e gera `characters-api.json` (22 grupos, sem array flat, com PNG+WebP links e guard de pastas com arte sem ficha) |')
$L.Add('| `build_historia_api.ps1` | 2. **OBRIGATÓRIO** — parseia `Historia/Aetheria_Dados_do_Mundo.md` e gera `historia-api.json` (16 regiões, 5 batalhas, 5 celestes, 22 raças, 10 rituais, com validação cruzada raça↔região↔batalha) |')
$L.Add('| `build_readme.ps1` | 3. Gera este `README.md` a partir do `characters-api.json` (seções descritivas manuais + elenco automático das 22 raças) |')
$L.Add('| `build_racas.ps1` | 4. Gera as 22 páginas em `racas/*.html` a partir da API (template único com payload `[ordered]` embutido, OG/Twitter meta, herói rotativo, rituais, guard de soma de membros contra JSON) |')
$L.Add('| `build_manifest.ps1` | 5. Gera `manifest.webmanifest` (PWA) com top 3 raças como shortcuts e contagens vivas |')
$L.Add('| `build_sitemap.ps1` | 6. Gera `sitemap.xml` a partir dos `racas/*.html` e HTMLs raiz (index, mapa, linha do tempo) |')
$L.Add('| `make_og_cover.ps1` | Gera a imagem de capa OG (`assets/og-cover.{jpg,png,svg}`) usada em todas as meta-tags de compartilhamento |')
$L.Add('| `absorb_sync.ps1` | Absorve pasta `NN_*` recriada na raiz pela sync externa do Bruno (idêntico por hash descarta, novo move, DIFERENTE guarda como `*.CONFLITO-SYNC.*`); rodar após cada sincronização OU atualizar o destino da sync para `...\Teste\codex\` |')
$L.Add('| `fix_encoding.ps1` | Repara mojibake double-encoded UTF-8↔CP1252 nos `.md`/`.ps1` (estratégia: por segmento, preservando partes já corretas; **SEMPRE rodar antes de qualquer diff**) |')
$L.Add('| `fix_image_typos.ps1` | Renomeia PNGs com typos inequívocos (Levenshtein ≤2 + pareamento único por pasta); casos ambíguos ignorados com aviso |')
$L.Add('| `dedupe_images.ps1` | Remove PNGs/WebPs duplicados por hash SHA-256 dentro de cada pasta `codex/NN_*` |')
$L.Add('| `check_missing_images.ps1` | Diagnóstico: classifica cada personagem sem imagem em SEM-ARTE (45), COLISÃO (8) ou EM-OUTRA-PASTA (2) — somente leitura |')
$L.Add('| `pad_demonios.py` | Padroniza `codex/05_Demonios/Aetheria_Codex_de_Demônios.md` no formato bulleted-bold (Python 3, UTF-8, idempotente, 6 asserts) |')
$L.Add('| `pad_preambulos.py` | Sincroniza os preâmbulos (texto antes do primeiro `## N.`) das 22 raças com a contagem real de fichas (regex mínima, idempotente) |')
$L.Add('| `relatorio_arte.py` | Gera `docs/relatorio-arte.md` (somente leitura) listando órfãos, cópias idênticas, homônimos e quase-duplicatas |')
$L.Add('')
$L.Add('## Formatos das Fichas (.md)')
$L.Add('')
$L.Add('Cada personagem começa numa linha numerada (`## N. Nome, epíteto` ou `N. Nome`) e os campos podem aparecer em **três estilos** — o parser da API aceita todos:')
$L.Add('')
$L.Add('1. **Bulleted-bold** (ex.: Humanos): `- **História Original:** texto...`')
$L.Add('2. **Texto simples** (ex.: Monstros): campos como parágrafos `História Original:` seguidos de linha em branco')
$L.Add('3. **Esquema Mutantes**: rótulos próprios — `Classe Mutagênica:`, `Anatomia & Detalhes:`, `Atributos Únicos:`')
$L.Add('')
$L.Add('Rótulos reconhecidos pelo parser (com variações): História Original · Raça/Categoria/Ordem/Classe Mutagênica/Demoníaca/Mutante · DNA & Raio-X Visual · Físico & Postura · Rosto & Cabelo/Anatomia/Detalhes · Vestuário · Paleta de Cores · Acessórios & Equipamento/Atributos Únicos.')
$L.Add('')
$L.Add('## Regras Importantes')
$L.Add('')
$L.Add('- **Encoding:** tudo em UTF-8; os `.ps1` precisam estar salvos **com BOM** (PowerShell 5.1). Nunca salvar `.md` em ANSI.')
$L.Add('- **Imagens:** o matching é estrito (nome exato ou normalizado, sem reuso entre personagens). PNG com nome errado fica órfão de propósito — ver `Memoria.md` se quiser recuperá-lo.')
$L.Add('- **README e API são gerados:** edite sempre os `.md` das pastas e regenere; nunca edite `README.md`/`characters-api.json` diretamente.')
$L.Add('- **Git versiona só textos:** PNGs ficam fora via `.gitignore` (~1,3 GB).')
$L.Add('')
$L.Add('## 🎛️ Comando «atualização de personagens»')
$L.Add('')
$L.Add('Quando disser **"personagens atualizados"**, **"atualização de personagem(s)"**, **"atualizei o codex"** ou **"checar o que mudou"**, o assistente deve executar o checklist padrão documentado em [`Memoria.md`](Memoria.md) (seção COMANDOS): reparar encoding → comparar elenco por pasta → escanear imagens novas/órfãs/duplicadas → regenerar API+README → relatório do que precisa de `.md`, de edição ou de nomes.')
$L.Add('')
$L.Add('## 🕸️ Grafo de Conhecimento (`/graphify`)')
$L.Add('')
$L.Add('O projeto tem um **grafo de conhecimento navegável em [`graphify-out/`](graphify-out/)**, gerado pela skill `/graphify`: **298 nós / 311 arestas / 72 comunidades** (snapshot de 02/09/2026 — reflete padronização Demônios, W7+W8 rituais, sincronização de preâmbulos e Bersek novo; labels rotulados em pt-BR via Louvain + override manual).')
$L.Add('')
$L.Add('Arquivos: `graph.html` (visualização interativa — abra no navegador) · `GRAPH_REPORT.md` (relatório com god nodes, conexões surpreendentes e perguntas sugeridas) · `graph.json` (dados brutos do grafo) · `manifest.json` + `cost.json` (estado p/ atualização incremental — 3 runs / 139k input / 48k output totais).')
$L.Add('')
$L.Add('**God nodes (top-10):** `abrirRitual()` 14 arestas · `Galeria Aetheria Codex` 13 · `boot()` 13 · `esc()` 12 · `goTo()` 10 · `splitTitle()` 7 · `renderStage()` 7 · `Codex dos Bersek de Aetheria (A Fúria do Último Voto)` 6 · `initParticles()` 6 · `buildRoster()` 6.')
$L.Add('')
$L.Add('**Hiperarestas principais:** 22 raças do codex (hyperedge canônica) · 8 personagens homônimos entre pastas (Ulthar, Vanek, Aurelion, Garrion, Kyran, Nyxaris, Stellaris, Vespera — marcados como variantes intencionais) · Conflito central Deuses/Aspectos vs Seres do Vazio (Erupção do Abismo).')
$L.Add('')
$L.Add('**Para assistentes de IA:** ao responder perguntas sobre lore, personagens, regiões, batalhas ou arquitetura do site, consulte o grafo em vez de re-ler tudo:')
$L.Add('')
$L.Add('- `/graphify query "pergunta"` — resposta atravessando o grafo (BFS amplo; `--dfs` rastreia um caminho; `--budget 1500` limita tokens)')
$L.Add('- `/graphify path "Entidade A" "Entidade B"` — caminho mais curto entre dois conceitos')
$L.Add('- `/graphify explain "NomeDoNo"` — explicação em linguagem simples de um nó')
$L.Add('- `/graphify --update` — re-extrai só arquivos novos/alterados (rodar após mudanças grandes de conteúdo)')
$L.Add('')
$L.Add('*O `graph.json` é um snapshot: depois de adicionar/editar muitas fichas ou páginas, rode `/graphify --update` para atualizá-lo. A skill detecta 128 nós isolados (lacunas de documentação) e 41 comunidades finas (<3 nós) — query explore ajuda a mapear.*')
$L.Add('')
$L.Add('## Como Rodar o Site')
$L.Add('')
$L.Add('O `fetch()` do JSON não funciona abrindo o arquivo direto no navegador (restrição de origem `file://`). Use um servidor local:')
$L.Add('')
$L.Add('```powershell')
$L.Add('# opção 1 - Python')
$L.Add('python -m http.server 8080')
$L.Add('# opção 2 - Node')
$L.Add('npx serve .')
$L.Add('```')
$L.Add('')
$L.Add('Depois abra `http://localhost:8080`.')
$L.Add('')
$L.Add('## Como Regenerar os Artefatos')
$L.Add('')
$L.Add('```powershell')
$L.Add('# 1. APIS (obrigatórias antes de qualquer outra)')
$L.Add('powershell -File scripts\build_api_json.ps1        # gera characters-api.json a partir das fichas .md')
$L.Add('powershell -File scripts\build_historia_api.ps1    # gera historia-api.json a partir de Historia/Aetheria_Dados_do_Mundo.md')
$L.Add('# 2. HTMLs + manifest + sitemap (consomem as APIs)')
$L.Add('powershell -File scripts\build_manifest.ps1        # gera manifest.webmanifest (PWA) com top 3 racas')
$L.Add('powershell -File scripts\build_sitemap.ps1         # gera sitemap.xml a partir de racas/*.html')
$L.Add('powershell -File scripts\build_racas.ps1           # gera as ' + $api.totalGroups + ' páginas de raça em racas/')
$L.Add('# 3. Documentação (lê o characters-api.json)')
$L.Add('powershell -File scripts\build_readme.ps1          # gera este README.md')
$L.Add('```')
$L.Add('')
$L.Add('## 🧪 Testes & Comandos npm')
$L.Add('')
$L.Add('Pipeline de validação local (`npm run all`, <30s) encadeia `validate` + `smoke` + `screens`. Pré-requisito: servidor local em `:8080` (`python -m http.server 8080` ou `npx serve .`).')
$L.Add('')
$L.Add('### Comandos disponíveis')
$L.Add('')
$L.Add('```bash')
$L.Add('npm run validate              # 1. validate-api.mjs (standalone, sem browser) — 22 grupos, slugs únicos, imagens existem')
$L.Add('npm run smoke                 # 2. smoke E2E (47 checks via Playwright local) — filtros, modal, Ctrl+K, contraste WCAG, reduced-motion, visible-focus, swipe touch, cross-fade, herói, rituais')
$L.Add('npm run screens               # 3. 6 capturas PNG 1600x1000 (claro/escuro/filtros/modal/Ctrl+K/mapa)')
$L.Add('npm run all                   # 4. validate + smoke + screens em sequência (= npm run all)')
$L.Add('')
$L.Add('# Checks individuais (regressão focada):')
$L.Add('npm run og-check              # meta-tags OG dinâmicas por personagem (18 checks)')
$L.Add('npm run share-check           # 3 botões de share no modal — Web Share + clipboard + embed (9 checks)')
$L.Add('npm run about-check           # dialog "Sobre" do footer (4 checks)')
$L.Add('npm run onboarding-check      # overlay de 4 passos, persistência, 4 saídas (11 checks)')
$L.Add('npm run a11y-empty-check      # MICRO_COPY 22 raças + top-3 empty state + skip-link (8 checks)')
$L.Add('npm run timeline-check        # página Linha_do_Tempo — 4 atos + 5 batalhas (12 checks)')
$L.Add('npm run narrativa-check       # rota narrativa entre 5 pins de batalha (13 checks)')
$L.Add('npm run mapa-filtros-check    # filtro de raça/era no mapa + deep-link (10 checks)')
$L.Add('npm run mapa-export-check     # export PNG da vista do mapa (9 checks)')
$L.Add('')
$L.Add('# Qualidade de código:')
$L.Add('npm run lint                  # ESLint (tests/) + markdownlint (raiz + scripts/**/*.md)')
$L.Add('npm run lint:js               # só ESLint')
$L.Add('npm run lint:md               # só markdownlint')
$L.Add('npm run format                # prettier --write .')
$L.Add('npm run format:check          # prettier --check . (CI mode)')
$L.Add('```')
$L.Add('')
$L.Add('### Dependências de desenvolvimento (5)')
$L.Add('')
$L.Add('| Pacote | Versão | Função |')
$L.Add('|---|---|---|')
$L.Add('| `eslint` | ^9.13.0 | Lint JS (flat config, escopo `tests/`, 6 regras mínimas: no-undef/no-var/eqeqeq/no-empty como error; no-unused-vars/prefer-const como warn) |')
$L.Add('| `globals` | ^15.11.0 | Pacote de globals Node para ESLint |')
$L.Add('| `prettier` | ^3.3.3 | Formatter (printWidth 100, trailingComma "none", endOfLine "lf") |')
$L.Add('| `markdownlint-cli` | ^0.42.0 | Lint Markdown (4 regras ativas: MD009/MD012/MD024/MD046; 7 desabilitadas por falso-positivo em prosa) |')
$L.Add('| `playwright` | ^1.62.1 | SDK de automação browser (Chromium headless) — usado por `tests/feature-shots.mjs` para capturar as 17 telas Q4/2026 em `docs/screenshots/feat-*.jpg` |')
$L.Add('')
$L.Add('**Regra zero-deps em runtime:** o site (`index.html`, `racas/*.html`, `Mapa_Aetheria.html`, `Linha_do_Tempo.html`) NÃO usa nenhuma biblioteca externa — GSAP foi removido em 02/09/2026; tudo é HTML + CSS + JS puro. As 5 deps acima são só para o pipeline de validação local + capturas de tela.')
$L.Add('')
$L.Add('### Testes utilitários (Python + Node)')
$L.Add('')
$L.Add('| Arquivo | Função |')
$L.Add('|---|---|')
$L.Add('| `tests/analyze.mjs` | Analisa os artefatos gerados e emite relatório HTML (página de QA local) |')
$L.Add('| `tests/convert_webp.py` | Pipeline PNG→WebP (489/489 convertido em 02/09; converte cada `codex/NN_*/X.png` em `X.webp` irmão) |')
$L.Add('| `tests/make-favicons.mjs` | Gera os favicons `favicon-{32,192}.png` e `apple-touch-icon.png` a partir do SVG canônico |')
$L.Add('| `tests/make-og-cover.mjs` | Gera a imagem de capa OG (`og-cover.{jpg,png}`) — wrapper Node do `scripts/make_og_cover.ps1` |')
$L.Add('| `tests/screenshots.mjs` | Captura as 6 telas principais (1600×1000) em `tests/screenshots/` (gerado, ignorado do git) |')
$L.Add('| `tests/feature-shots.mjs` | Captura as 17 telas das features Q4/2026 (10 desktop 1600×1000 + 7 mobile 390×844) em `docs/screenshots/feat-*.jpg` — galeria visual deste README |')
$L.Add('| `tests/validate-api.mjs` | Valida o `characters-api.json` standalone: 22 grupos, slugs únicos, todas imagens existem em disco, 2 avisos esperados (homônimos Ulthar/Vanek) |')
$L.Add('')
$L.Add('**Convenção de testes Playwright:** `serviceWorkers: "block"` em todos os 12 contextos (Lição 11ª — SW segura versão antiga em testes), `permissions: ["clipboard-read", "clipboard-write"]` para os share-checks, `installPageListeners(page)` em cada bloco (helper que captura `pageerror` + console error + HTTP ≥ 400 + `requestfailed` de JS/CSS/fonts).')
$L.Add('')
$L.Add('## Resumo Por Categoria')
$L.Add('')
$L.Add('Total: **' + $api.totalCharacters + ' personagens** em **' + $api.totalGroups + ' categorias** (API gerada em ' + $api.generatedAt + ').')
$L.Add('')

foreach ($g in $api.groups) {
  $L.Add('<details>')
  $L.Add('<summary><strong>' + $g.folder + '</strong> — ' + $g.count + ' personagens <code>' + $g.file + '</code></summary>')
  $L.Add('')
  if ($g.count -gt 0) {
    $L.Add(($g.characters | ForEach-Object { $_.title }) -join ' | ')
  } else {
    $L.Add('Sem personagens registrados no momento.')
  }
  $L.Add('')
  $L.Add('</details>')
  $L.Add('')
}

$L.Add('## API JSON — Formato dos Dados')
$L.Add('')
$L.Add('```json')
$L.Add('{')
$L.Add('  "project": "Aetheria Codex",')
$L.Add('  "generatedAt": "' + $api.generatedAt + '",')
$L.Add('  "totalGroups": ' + $api.totalGroups + ',')
$L.Add('  "totalCharacters": ' + $api.totalCharacters + ',')
$L.Add('  "groups":  [ { "folder": "...", "file": "...", "count": N, "characters": [...] } ]')
$L.Add('')
$L.Add('> O array flat `"characters"` saiu do JSON em 26/08/2026: ele duplicava `groups[].characters` e já havia divergido uma vez. Derive a lista plana dos grupos quando precisar.')
$L.Add('}')
$L.Add('```')
$L.Add('')
$L.Add('Cada personagem tem:')
$L.Add('')
$L.Add('| Campo | Conteúdo |')
$L.Add('|---|---|')
$L.Add('| `number` | número na ficha |')
$L.Add('| `title` | nome completo com epíteto ("X, o Y") |')
$L.Add('| `name` / `id` | nome base (sem epíteto) |')
$L.Add('| `file` / `folder` | origem no acervo |')
$L.Add('| `image` | caminho relativo do PNG ou `null` |')
$L.Add('| `description` | história original extraída |')
$L.Add('| `attributes` | `race`, `physical`, `faceAndHair`, `outfit`, `palette`, `equipment` (quando existirem na ficha) |')
$L.Add('')
$L.Add('### Exemplo de uso em JavaScript')
$L.Add('')
$L.Add('```js')
$L.Add('const api = await (await fetch("./characters-api.json")).json();')
$L.Add('')
$L.Add('const gigantes = api.groups.find((grupo) => grupo.folder === "07_Gigantes");')
$L.Add('console.log(gigantes.count);')
$L.Add('console.log(gigantes.characters.filter((c) => c.folder === "07_Gigantes"));')
$L.Add('```')
$L.Add('')
$L.Add('---')
$L.Add('')
$L.Add('## 📂 Arquivos Necessários para Entender o Projeto (leia nesta ordem)')
$L.Add('')
$L.Add('> **Para assistentes de IA em uma nova sessão:** leia **nesta ordem** para absorver todo o contexto do projeto antes de qualquer alteração. O **passo 1 (`Memoria.md`) é obrigatório** — lá está a linha do tempo oficial, regras (ex.: `.claude/settings.json` NUNCA é commitado), armadilhas de PowerShell 5.1 e pendências de conteúdo.')
$L.Add('')
$L.Add('Para compreender completamente este projeto, leia os seguintes arquivos na ordem sugerida:')
$L.Add('')
$L.Add('1. **README.md** (este arquivo) — visão geral, estrutura, dependências, comandos, scripts e funcionamento')
$L.Add('2. **Memoria.md** — linha do tempo oficial, alterações, erros resolvidos, lições técnicas e pendências; leia PRIMEIRO em qualquer sessão')
$L.Add('3. **Temporario.md** — backlog Q4/2026 consolidado (status dos 10 itens + 39 subitens, sugestões de próximas sessões)')
$L.Add('4. **index.html** — site galeria estático (consome `characters-api.json`; tema claro/escuro, busca, filtros, modal, paleta Ctrl+K, PWA, onboarding, share/embed)')
$L.Add('5. **Mapa_Aetheria.html** — mapa 3D do mundo (consome `historia-api.json`; Canvas 2D puro, 26 pins, filtro raça/era, export PNG, rota narrativa)')
$L.Add('6. **Linha_do_Tempo.html** + **assets/timeline.css** + **assets/timeline-data.js** — linha narrativa do mundo (4 atos + 5 batalhas)')
$L.Add('7. **offline.html** + **sw.js** + **manifest.webmanifest** — PWA completa (Service Worker, fallback offline, manifesto com 3 ícones + 4 shortcuts)')
$L.Add('8. **assets/codex.css** (105 KB) — CSS principal do site (extraído do `index.html` em 03/09; cacheável cross-page)')
$L.Add('9. **assets/rituals.js** — motor de 10 rituais do modal (3 Demônios + 2 Onis + 1 cada em Humanos/Semideuses/Deuses/Monstros/Meio-Sangue)')
$L.Add('10. **assets/transitions.js** — transições de página (04_Onis vídeo + 05_Demonios portão; importado pelo `index.html`)')
$L.Add('11. **racas/assets/raca.js** + **racas/assets/raca.css** — assets das 22 páginas de raça geradas (herói rotativo, rituais, partículas, reveal)')
$L.Add('12. **data/themes.json** — tabela única de cor/ícone/label das 22 raças (fonte canônica; carregada por `index.html` e `build_racas.ps1`)')
$L.Add('13. **data/characters.schema.json** — schema JSON da API de personagens (referência para validação; doc pendente §5.3)')
$L.Add('14. **characters-api.json** — API estática de personagens (gerada por `scripts/build_api_json.ps1`)')
$L.Add('15. **historia-api.json** — API estática da história (gerada por `scripts/build_historia_api.ps1`; inclui `rituais[]` desde 02/09)')
$L.Add('16. **scripts/build_api_json.ps1** — gerador da API de personagens (PowerShell 5.1 + BOM; 3 formatos de ficha aceitos)')
$L.Add('17. **scripts/build_historia_api.ps1** — gerador da API da história (suporta `## RITUAL:` desde 02/09)')
$L.Add('18. **scripts/build_racas.ps1** — gerador das 22 páginas de raça (`racas/`)')
$L.Add('19. **scripts/build_readme.ps1** — gerador deste próprio README.md')
$L.Add('20. **scripts/build_manifest.ps1** + **scripts/build_sitemap.ps1** + **scripts/make_og_cover.ps1** — geradores de PWA + sitemap + OG cover')
$L.Add('21. **scripts/fix_encoding.ps1** + **fix_image_typos.ps1** + **dedupe_images.ps1** + **check_missing_images.ps1** + **absorb_sync.ps1** — utilitários de manutenção')
$L.Add('22. **scripts/pad_demonios.py** + **pad_preambulos.py** + **relatorio_arte.py** — utilitários Python (padronização de fichas, sincronização de preâmbulos, relatório de arte)')
$L.Add('23. **tests/validate-api.mjs** + **tests/smoke.mjs** + **tests/screenshots.mjs** — pipeline `npm run all` (validate + smoke 47 checks + 6 screenshots)')
$L.Add('24. **tests/og-check.mjs** + **share-check.mjs** + **about-check.mjs** + **onboarding-check.mjs** + **a11y-empty-check.mjs** + **timeline-check.mjs** + **narrativa-check.mjs** + **mapa-filtros-check.mjs** + **mapa-export-check.mjs** — 9 checks focados (88 asserções totais)')
$L.Add('25. **package.json** + **.prettierrc** + **eslint.config.js** + **.markdownlint.json** — tooling de qualidade (`npm run lint`, `npm run format:check`)')
$L.Add('26. **docs/screenshots/** (28 capturas JPEG: 11 galeria base + 17 Q4/2026) + **docs/relatorio-arte.md** — material visual e diagnóstico de conteúdo')
$L.Add('27. **graphify-out/** — grafo de conhecimento (`/graphify` — 298 nós / 311 arestas / 72 comunidades)')
$L.Add('28. **codex/** — fichas `.md` e imagens `.png`/`.webp` dos ' + $api.totalCharacters + ' personagens (fonte primária; 22 pastas numeradas)')
$L.Add('29. **Historia/** — lore autoral do mundo (4 `.md`: Aetheria_Codex_do_Mundo, Aetheria_Dados_do_Mundo, Aetheria_Geografia_e_Batalhas, Aetheria_Super_Historia)')
$L.Add('')
$L.Add('---')
$L.Add('')
$L.Add('## 🌐 Link Publicado')
$L.Add('')
$L.Add('Site publicado: https://bsmiguell.github.io/Temporario/')
$L.Add('Sitemap: https://bsmiguell.github.io/Temporario/sitemap.xml')
$L.Add('')
$L.Add('---')
$L.Add('')
$L.Add('*Última geração: ' + (Get-Date -Format 'dd/MM/yyyy HH:mm') + ' por `build_readme.ps1`. Histórico e pendências: [`Memoria.md`](Memoria.md).*')

$content = $L -join [Environment]::NewLine
[System.IO.File]::WriteAllText((Join-Path $root 'README.md'), $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "README.md gerado."
